// Code generated by ent, DO NOT EDIT.

package activity

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/glanceapp/glance/pkg/storage/postgres/ent/predicate"
	pgvector "github.com/pgvector/pgvector-go"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.Activity {
	return predicate.Activity(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.Activity {
	return predicate.Activity(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.Activity {
	return predicate.Activity(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.Activity {
	return predicate.Activity(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.Activity {
	return predicate.Activity(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.Activity {
	return predicate.Activity(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.Activity {
	return predicate.Activity(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.Activity {
	return predicate.Activity(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.Activity {
	return predicate.Activity(sql.FieldLTE(FieldID, id))
}

// IDEqualFold applies the EqualFold predicate on the ID field.
func IDEqualFold(id string) predicate.Activity {
	return predicate.Activity(sql.FieldEqualFold(FieldID, id))
}

// IDContainsFold applies the ContainsFold predicate on the ID field.
func IDContainsFold(id string) predicate.Activity {
	return predicate.Activity(sql.FieldContainsFold(FieldID, id))
}

// UID applies equality check predicate on the "uid" field. It's identical to UIDEQ.
func UID(v string) predicate.Activity {
	return predicate.Activity(sql.FieldEQ(FieldUID, v))
}

// SourceUID applies equality check predicate on the "source_uid" field. It's identical to SourceUIDEQ.
func SourceUID(v string) predicate.Activity {
	return predicate.Activity(sql.FieldEQ(FieldSourceUID, v))
}

// SourceType applies equality check predicate on the "source_type" field. It's identical to SourceTypeEQ.
func SourceType(v string) predicate.Activity {
	return predicate.Activity(sql.FieldEQ(FieldSourceType, v))
}

// Title applies equality check predicate on the "title" field. It's identical to TitleEQ.
func Title(v string) predicate.Activity {
	return predicate.Activity(sql.FieldEQ(FieldTitle, v))
}

// Body applies equality check predicate on the "body" field. It's identical to BodyEQ.
func Body(v string) predicate.Activity {
	return predicate.Activity(sql.FieldEQ(FieldBody, v))
}

// URL applies equality check predicate on the "url" field. It's identical to URLEQ.
func URL(v string) predicate.Activity {
	return predicate.Activity(sql.FieldEQ(FieldURL, v))
}

// ImageURL applies equality check predicate on the "image_url" field. It's identical to ImageURLEQ.
func ImageURL(v string) predicate.Activity {
	return predicate.Activity(sql.FieldEQ(FieldImageURL, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Activity {
	return predicate.Activity(sql.FieldEQ(FieldCreatedAt, v))
}

// ShortSummary applies equality check predicate on the "short_summary" field. It's identical to ShortSummaryEQ.
func ShortSummary(v string) predicate.Activity {
	return predicate.Activity(sql.FieldEQ(FieldShortSummary, v))
}

// FullSummary applies equality check predicate on the "full_summary" field. It's identical to FullSummaryEQ.
func FullSummary(v string) predicate.Activity {
	return predicate.Activity(sql.FieldEQ(FieldFullSummary, v))
}

// RawJSON applies equality check predicate on the "raw_json" field. It's identical to RawJSONEQ.
func RawJSON(v string) predicate.Activity {
	return predicate.Activity(sql.FieldEQ(FieldRawJSON, v))
}

// Embedding applies equality check predicate on the "embedding" field. It's identical to EmbeddingEQ.
func Embedding(v pgvector.Vector) predicate.Activity {
	return predicate.Activity(sql.FieldEQ(FieldEmbedding, v))
}

// UIDEQ applies the EQ predicate on the "uid" field.
func UIDEQ(v string) predicate.Activity {
	return predicate.Activity(sql.FieldEQ(FieldUID, v))
}

// UIDNEQ applies the NEQ predicate on the "uid" field.
func UIDNEQ(v string) predicate.Activity {
	return predicate.Activity(sql.FieldNEQ(FieldUID, v))
}

// UIDIn applies the In predicate on the "uid" field.
func UIDIn(vs ...string) predicate.Activity {
	return predicate.Activity(sql.FieldIn(FieldUID, vs...))
}

// UIDNotIn applies the NotIn predicate on the "uid" field.
func UIDNotIn(vs ...string) predicate.Activity {
	return predicate.Activity(sql.FieldNotIn(FieldUID, vs...))
}

// UIDGT applies the GT predicate on the "uid" field.
func UIDGT(v string) predicate.Activity {
	return predicate.Activity(sql.FieldGT(FieldUID, v))
}

// UIDGTE applies the GTE predicate on the "uid" field.
func UIDGTE(v string) predicate.Activity {
	return predicate.Activity(sql.FieldGTE(FieldUID, v))
}

// UIDLT applies the LT predicate on the "uid" field.
func UIDLT(v string) predicate.Activity {
	return predicate.Activity(sql.FieldLT(FieldUID, v))
}

// UIDLTE applies the LTE predicate on the "uid" field.
func UIDLTE(v string) predicate.Activity {
	return predicate.Activity(sql.FieldLTE(FieldUID, v))
}

// UIDContains applies the Contains predicate on the "uid" field.
func UIDContains(v string) predicate.Activity {
	return predicate.Activity(sql.FieldContains(FieldUID, v))
}

// UIDHasPrefix applies the HasPrefix predicate on the "uid" field.
func UIDHasPrefix(v string) predicate.Activity {
	return predicate.Activity(sql.FieldHasPrefix(FieldUID, v))
}

// UIDHasSuffix applies the HasSuffix predicate on the "uid" field.
func UIDHasSuffix(v string) predicate.Activity {
	return predicate.Activity(sql.FieldHasSuffix(FieldUID, v))
}

// UIDEqualFold applies the EqualFold predicate on the "uid" field.
func UIDEqualFold(v string) predicate.Activity {
	return predicate.Activity(sql.FieldEqualFold(FieldUID, v))
}

// UIDContainsFold applies the ContainsFold predicate on the "uid" field.
func UIDContainsFold(v string) predicate.Activity {
	return predicate.Activity(sql.FieldContainsFold(FieldUID, v))
}

// SourceUIDEQ applies the EQ predicate on the "source_uid" field.
func SourceUIDEQ(v string) predicate.Activity {
	return predicate.Activity(sql.FieldEQ(FieldSourceUID, v))
}

// SourceUIDNEQ applies the NEQ predicate on the "source_uid" field.
func SourceUIDNEQ(v string) predicate.Activity {
	return predicate.Activity(sql.FieldNEQ(FieldSourceUID, v))
}

// SourceUIDIn applies the In predicate on the "source_uid" field.
func SourceUIDIn(vs ...string) predicate.Activity {
	return predicate.Activity(sql.FieldIn(FieldSourceUID, vs...))
}

// SourceUIDNotIn applies the NotIn predicate on the "source_uid" field.
func SourceUIDNotIn(vs ...string) predicate.Activity {
	return predicate.Activity(sql.FieldNotIn(FieldSourceUID, vs...))
}

// SourceUIDGT applies the GT predicate on the "source_uid" field.
func SourceUIDGT(v string) predicate.Activity {
	return predicate.Activity(sql.FieldGT(FieldSourceUID, v))
}

// SourceUIDGTE applies the GTE predicate on the "source_uid" field.
func SourceUIDGTE(v string) predicate.Activity {
	return predicate.Activity(sql.FieldGTE(FieldSourceUID, v))
}

// SourceUIDLT applies the LT predicate on the "source_uid" field.
func SourceUIDLT(v string) predicate.Activity {
	return predicate.Activity(sql.FieldLT(FieldSourceUID, v))
}

// SourceUIDLTE applies the LTE predicate on the "source_uid" field.
func SourceUIDLTE(v string) predicate.Activity {
	return predicate.Activity(sql.FieldLTE(FieldSourceUID, v))
}

// SourceUIDContains applies the Contains predicate on the "source_uid" field.
func SourceUIDContains(v string) predicate.Activity {
	return predicate.Activity(sql.FieldContains(FieldSourceUID, v))
}

// SourceUIDHasPrefix applies the HasPrefix predicate on the "source_uid" field.
func SourceUIDHasPrefix(v string) predicate.Activity {
	return predicate.Activity(sql.FieldHasPrefix(FieldSourceUID, v))
}

// SourceUIDHasSuffix applies the HasSuffix predicate on the "source_uid" field.
func SourceUIDHasSuffix(v string) predicate.Activity {
	return predicate.Activity(sql.FieldHasSuffix(FieldSourceUID, v))
}

// SourceUIDEqualFold applies the EqualFold predicate on the "source_uid" field.
func SourceUIDEqualFold(v string) predicate.Activity {
	return predicate.Activity(sql.FieldEqualFold(FieldSourceUID, v))
}

// SourceUIDContainsFold applies the ContainsFold predicate on the "source_uid" field.
func SourceUIDContainsFold(v string) predicate.Activity {
	return predicate.Activity(sql.FieldContainsFold(FieldSourceUID, v))
}

// SourceTypeEQ applies the EQ predicate on the "source_type" field.
func SourceTypeEQ(v string) predicate.Activity {
	return predicate.Activity(sql.FieldEQ(FieldSourceType, v))
}

// SourceTypeNEQ applies the NEQ predicate on the "source_type" field.
func SourceTypeNEQ(v string) predicate.Activity {
	return predicate.Activity(sql.FieldNEQ(FieldSourceType, v))
}

// SourceTypeIn applies the In predicate on the "source_type" field.
func SourceTypeIn(vs ...string) predicate.Activity {
	return predicate.Activity(sql.FieldIn(FieldSourceType, vs...))
}

// SourceTypeNotIn applies the NotIn predicate on the "source_type" field.
func SourceTypeNotIn(vs ...string) predicate.Activity {
	return predicate.Activity(sql.FieldNotIn(FieldSourceType, vs...))
}

// SourceTypeGT applies the GT predicate on the "source_type" field.
func SourceTypeGT(v string) predicate.Activity {
	return predicate.Activity(sql.FieldGT(FieldSourceType, v))
}

// SourceTypeGTE applies the GTE predicate on the "source_type" field.
func SourceTypeGTE(v string) predicate.Activity {
	return predicate.Activity(sql.FieldGTE(FieldSourceType, v))
}

// SourceTypeLT applies the LT predicate on the "source_type" field.
func SourceTypeLT(v string) predicate.Activity {
	return predicate.Activity(sql.FieldLT(FieldSourceType, v))
}

// SourceTypeLTE applies the LTE predicate on the "source_type" field.
func SourceTypeLTE(v string) predicate.Activity {
	return predicate.Activity(sql.FieldLTE(FieldSourceType, v))
}

// SourceTypeContains applies the Contains predicate on the "source_type" field.
func SourceTypeContains(v string) predicate.Activity {
	return predicate.Activity(sql.FieldContains(FieldSourceType, v))
}

// SourceTypeHasPrefix applies the HasPrefix predicate on the "source_type" field.
func SourceTypeHasPrefix(v string) predicate.Activity {
	return predicate.Activity(sql.FieldHasPrefix(FieldSourceType, v))
}

// SourceTypeHasSuffix applies the HasSuffix predicate on the "source_type" field.
func SourceTypeHasSuffix(v string) predicate.Activity {
	return predicate.Activity(sql.FieldHasSuffix(FieldSourceType, v))
}

// SourceTypeEqualFold applies the EqualFold predicate on the "source_type" field.
func SourceTypeEqualFold(v string) predicate.Activity {
	return predicate.Activity(sql.FieldEqualFold(FieldSourceType, v))
}

// SourceTypeContainsFold applies the ContainsFold predicate on the "source_type" field.
func SourceTypeContainsFold(v string) predicate.Activity {
	return predicate.Activity(sql.FieldContainsFold(FieldSourceType, v))
}

// TitleEQ applies the EQ predicate on the "title" field.
func TitleEQ(v string) predicate.Activity {
	return predicate.Activity(sql.FieldEQ(FieldTitle, v))
}

// TitleNEQ applies the NEQ predicate on the "title" field.
func TitleNEQ(v string) predicate.Activity {
	return predicate.Activity(sql.FieldNEQ(FieldTitle, v))
}

// TitleIn applies the In predicate on the "title" field.
func TitleIn(vs ...string) predicate.Activity {
	return predicate.Activity(sql.FieldIn(FieldTitle, vs...))
}

// TitleNotIn applies the NotIn predicate on the "title" field.
func TitleNotIn(vs ...string) predicate.Activity {
	return predicate.Activity(sql.FieldNotIn(FieldTitle, vs...))
}

// TitleGT applies the GT predicate on the "title" field.
func TitleGT(v string) predicate.Activity {
	return predicate.Activity(sql.FieldGT(FieldTitle, v))
}

// TitleGTE applies the GTE predicate on the "title" field.
func TitleGTE(v string) predicate.Activity {
	return predicate.Activity(sql.FieldGTE(FieldTitle, v))
}

// TitleLT applies the LT predicate on the "title" field.
func TitleLT(v string) predicate.Activity {
	return predicate.Activity(sql.FieldLT(FieldTitle, v))
}

// TitleLTE applies the LTE predicate on the "title" field.
func TitleLTE(v string) predicate.Activity {
	return predicate.Activity(sql.FieldLTE(FieldTitle, v))
}

// TitleContains applies the Contains predicate on the "title" field.
func TitleContains(v string) predicate.Activity {
	return predicate.Activity(sql.FieldContains(FieldTitle, v))
}

// TitleHasPrefix applies the HasPrefix predicate on the "title" field.
func TitleHasPrefix(v string) predicate.Activity {
	return predicate.Activity(sql.FieldHasPrefix(FieldTitle, v))
}

// TitleHasSuffix applies the HasSuffix predicate on the "title" field.
func TitleHasSuffix(v string) predicate.Activity {
	return predicate.Activity(sql.FieldHasSuffix(FieldTitle, v))
}

// TitleEqualFold applies the EqualFold predicate on the "title" field.
func TitleEqualFold(v string) predicate.Activity {
	return predicate.Activity(sql.FieldEqualFold(FieldTitle, v))
}

// TitleContainsFold applies the ContainsFold predicate on the "title" field.
func TitleContainsFold(v string) predicate.Activity {
	return predicate.Activity(sql.FieldContainsFold(FieldTitle, v))
}

// BodyEQ applies the EQ predicate on the "body" field.
func BodyEQ(v string) predicate.Activity {
	return predicate.Activity(sql.FieldEQ(FieldBody, v))
}

// BodyNEQ applies the NEQ predicate on the "body" field.
func BodyNEQ(v string) predicate.Activity {
	return predicate.Activity(sql.FieldNEQ(FieldBody, v))
}

// BodyIn applies the In predicate on the "body" field.
func BodyIn(vs ...string) predicate.Activity {
	return predicate.Activity(sql.FieldIn(FieldBody, vs...))
}

// BodyNotIn applies the NotIn predicate on the "body" field.
func BodyNotIn(vs ...string) predicate.Activity {
	return predicate.Activity(sql.FieldNotIn(FieldBody, vs...))
}

// BodyGT applies the GT predicate on the "body" field.
func BodyGT(v string) predicate.Activity {
	return predicate.Activity(sql.FieldGT(FieldBody, v))
}

// BodyGTE applies the GTE predicate on the "body" field.
func BodyGTE(v string) predicate.Activity {
	return predicate.Activity(sql.FieldGTE(FieldBody, v))
}

// BodyLT applies the LT predicate on the "body" field.
func BodyLT(v string) predicate.Activity {
	return predicate.Activity(sql.FieldLT(FieldBody, v))
}

// BodyLTE applies the LTE predicate on the "body" field.
func BodyLTE(v string) predicate.Activity {
	return predicate.Activity(sql.FieldLTE(FieldBody, v))
}

// BodyContains applies the Contains predicate on the "body" field.
func BodyContains(v string) predicate.Activity {
	return predicate.Activity(sql.FieldContains(FieldBody, v))
}

// BodyHasPrefix applies the HasPrefix predicate on the "body" field.
func BodyHasPrefix(v string) predicate.Activity {
	return predicate.Activity(sql.FieldHasPrefix(FieldBody, v))
}

// BodyHasSuffix applies the HasSuffix predicate on the "body" field.
func BodyHasSuffix(v string) predicate.Activity {
	return predicate.Activity(sql.FieldHasSuffix(FieldBody, v))
}

// BodyEqualFold applies the EqualFold predicate on the "body" field.
func BodyEqualFold(v string) predicate.Activity {
	return predicate.Activity(sql.FieldEqualFold(FieldBody, v))
}

// BodyContainsFold applies the ContainsFold predicate on the "body" field.
func BodyContainsFold(v string) predicate.Activity {
	return predicate.Activity(sql.FieldContainsFold(FieldBody, v))
}

// URLEQ applies the EQ predicate on the "url" field.
func URLEQ(v string) predicate.Activity {
	return predicate.Activity(sql.FieldEQ(FieldURL, v))
}

// URLNEQ applies the NEQ predicate on the "url" field.
func URLNEQ(v string) predicate.Activity {
	return predicate.Activity(sql.FieldNEQ(FieldURL, v))
}

// URLIn applies the In predicate on the "url" field.
func URLIn(vs ...string) predicate.Activity {
	return predicate.Activity(sql.FieldIn(FieldURL, vs...))
}

// URLNotIn applies the NotIn predicate on the "url" field.
func URLNotIn(vs ...string) predicate.Activity {
	return predicate.Activity(sql.FieldNotIn(FieldURL, vs...))
}

// URLGT applies the GT predicate on the "url" field.
func URLGT(v string) predicate.Activity {
	return predicate.Activity(sql.FieldGT(FieldURL, v))
}

// URLGTE applies the GTE predicate on the "url" field.
func URLGTE(v string) predicate.Activity {
	return predicate.Activity(sql.FieldGTE(FieldURL, v))
}

// URLLT applies the LT predicate on the "url" field.
func URLLT(v string) predicate.Activity {
	return predicate.Activity(sql.FieldLT(FieldURL, v))
}

// URLLTE applies the LTE predicate on the "url" field.
func URLLTE(v string) predicate.Activity {
	return predicate.Activity(sql.FieldLTE(FieldURL, v))
}

// URLContains applies the Contains predicate on the "url" field.
func URLContains(v string) predicate.Activity {
	return predicate.Activity(sql.FieldContains(FieldURL, v))
}

// URLHasPrefix applies the HasPrefix predicate on the "url" field.
func URLHasPrefix(v string) predicate.Activity {
	return predicate.Activity(sql.FieldHasPrefix(FieldURL, v))
}

// URLHasSuffix applies the HasSuffix predicate on the "url" field.
func URLHasSuffix(v string) predicate.Activity {
	return predicate.Activity(sql.FieldHasSuffix(FieldURL, v))
}

// URLEqualFold applies the EqualFold predicate on the "url" field.
func URLEqualFold(v string) predicate.Activity {
	return predicate.Activity(sql.FieldEqualFold(FieldURL, v))
}

// URLContainsFold applies the ContainsFold predicate on the "url" field.
func URLContainsFold(v string) predicate.Activity {
	return predicate.Activity(sql.FieldContainsFold(FieldURL, v))
}

// ImageURLEQ applies the EQ predicate on the "image_url" field.
func ImageURLEQ(v string) predicate.Activity {
	return predicate.Activity(sql.FieldEQ(FieldImageURL, v))
}

// ImageURLNEQ applies the NEQ predicate on the "image_url" field.
func ImageURLNEQ(v string) predicate.Activity {
	return predicate.Activity(sql.FieldNEQ(FieldImageURL, v))
}

// ImageURLIn applies the In predicate on the "image_url" field.
func ImageURLIn(vs ...string) predicate.Activity {
	return predicate.Activity(sql.FieldIn(FieldImageURL, vs...))
}

// ImageURLNotIn applies the NotIn predicate on the "image_url" field.
func ImageURLNotIn(vs ...string) predicate.Activity {
	return predicate.Activity(sql.FieldNotIn(FieldImageURL, vs...))
}

// ImageURLGT applies the GT predicate on the "image_url" field.
func ImageURLGT(v string) predicate.Activity {
	return predicate.Activity(sql.FieldGT(FieldImageURL, v))
}

// ImageURLGTE applies the GTE predicate on the "image_url" field.
func ImageURLGTE(v string) predicate.Activity {
	return predicate.Activity(sql.FieldGTE(FieldImageURL, v))
}

// ImageURLLT applies the LT predicate on the "image_url" field.
func ImageURLLT(v string) predicate.Activity {
	return predicate.Activity(sql.FieldLT(FieldImageURL, v))
}

// ImageURLLTE applies the LTE predicate on the "image_url" field.
func ImageURLLTE(v string) predicate.Activity {
	return predicate.Activity(sql.FieldLTE(FieldImageURL, v))
}

// ImageURLContains applies the Contains predicate on the "image_url" field.
func ImageURLContains(v string) predicate.Activity {
	return predicate.Activity(sql.FieldContains(FieldImageURL, v))
}

// ImageURLHasPrefix applies the HasPrefix predicate on the "image_url" field.
func ImageURLHasPrefix(v string) predicate.Activity {
	return predicate.Activity(sql.FieldHasPrefix(FieldImageURL, v))
}

// ImageURLHasSuffix applies the HasSuffix predicate on the "image_url" field.
func ImageURLHasSuffix(v string) predicate.Activity {
	return predicate.Activity(sql.FieldHasSuffix(FieldImageURL, v))
}

// ImageURLEqualFold applies the EqualFold predicate on the "image_url" field.
func ImageURLEqualFold(v string) predicate.Activity {
	return predicate.Activity(sql.FieldEqualFold(FieldImageURL, v))
}

// ImageURLContainsFold applies the ContainsFold predicate on the "image_url" field.
func ImageURLContainsFold(v string) predicate.Activity {
	return predicate.Activity(sql.FieldContainsFold(FieldImageURL, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.Activity {
	return predicate.Activity(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.Activity {
	return predicate.Activity(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.Activity {
	return predicate.Activity(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Activity {
	return predicate.Activity(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.Activity {
	return predicate.Activity(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.Activity {
	return predicate.Activity(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.Activity {
	return predicate.Activity(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.Activity {
	return predicate.Activity(sql.FieldLTE(FieldCreatedAt, v))
}

// ShortSummaryEQ applies the EQ predicate on the "short_summary" field.
func ShortSummaryEQ(v string) predicate.Activity {
	return predicate.Activity(sql.FieldEQ(FieldShortSummary, v))
}

// ShortSummaryNEQ applies the NEQ predicate on the "short_summary" field.
func ShortSummaryNEQ(v string) predicate.Activity {
	return predicate.Activity(sql.FieldNEQ(FieldShortSummary, v))
}

// ShortSummaryIn applies the In predicate on the "short_summary" field.
func ShortSummaryIn(vs ...string) predicate.Activity {
	return predicate.Activity(sql.FieldIn(FieldShortSummary, vs...))
}

// ShortSummaryNotIn applies the NotIn predicate on the "short_summary" field.
func ShortSummaryNotIn(vs ...string) predicate.Activity {
	return predicate.Activity(sql.FieldNotIn(FieldShortSummary, vs...))
}

// ShortSummaryGT applies the GT predicate on the "short_summary" field.
func ShortSummaryGT(v string) predicate.Activity {
	return predicate.Activity(sql.FieldGT(FieldShortSummary, v))
}

// ShortSummaryGTE applies the GTE predicate on the "short_summary" field.
func ShortSummaryGTE(v string) predicate.Activity {
	return predicate.Activity(sql.FieldGTE(FieldShortSummary, v))
}

// ShortSummaryLT applies the LT predicate on the "short_summary" field.
func ShortSummaryLT(v string) predicate.Activity {
	return predicate.Activity(sql.FieldLT(FieldShortSummary, v))
}

// ShortSummaryLTE applies the LTE predicate on the "short_summary" field.
func ShortSummaryLTE(v string) predicate.Activity {
	return predicate.Activity(sql.FieldLTE(FieldShortSummary, v))
}

// ShortSummaryContains applies the Contains predicate on the "short_summary" field.
func ShortSummaryContains(v string) predicate.Activity {
	return predicate.Activity(sql.FieldContains(FieldShortSummary, v))
}

// ShortSummaryHasPrefix applies the HasPrefix predicate on the "short_summary" field.
func ShortSummaryHasPrefix(v string) predicate.Activity {
	return predicate.Activity(sql.FieldHasPrefix(FieldShortSummary, v))
}

// ShortSummaryHasSuffix applies the HasSuffix predicate on the "short_summary" field.
func ShortSummaryHasSuffix(v string) predicate.Activity {
	return predicate.Activity(sql.FieldHasSuffix(FieldShortSummary, v))
}

// ShortSummaryEqualFold applies the EqualFold predicate on the "short_summary" field.
func ShortSummaryEqualFold(v string) predicate.Activity {
	return predicate.Activity(sql.FieldEqualFold(FieldShortSummary, v))
}

// ShortSummaryContainsFold applies the ContainsFold predicate on the "short_summary" field.
func ShortSummaryContainsFold(v string) predicate.Activity {
	return predicate.Activity(sql.FieldContainsFold(FieldShortSummary, v))
}

// FullSummaryEQ applies the EQ predicate on the "full_summary" field.
func FullSummaryEQ(v string) predicate.Activity {
	return predicate.Activity(sql.FieldEQ(FieldFullSummary, v))
}

// FullSummaryNEQ applies the NEQ predicate on the "full_summary" field.
func FullSummaryNEQ(v string) predicate.Activity {
	return predicate.Activity(sql.FieldNEQ(FieldFullSummary, v))
}

// FullSummaryIn applies the In predicate on the "full_summary" field.
func FullSummaryIn(vs ...string) predicate.Activity {
	return predicate.Activity(sql.FieldIn(FieldFullSummary, vs...))
}

// FullSummaryNotIn applies the NotIn predicate on the "full_summary" field.
func FullSummaryNotIn(vs ...string) predicate.Activity {
	return predicate.Activity(sql.FieldNotIn(FieldFullSummary, vs...))
}

// FullSummaryGT applies the GT predicate on the "full_summary" field.
func FullSummaryGT(v string) predicate.Activity {
	return predicate.Activity(sql.FieldGT(FieldFullSummary, v))
}

// FullSummaryGTE applies the GTE predicate on the "full_summary" field.
func FullSummaryGTE(v string) predicate.Activity {
	return predicate.Activity(sql.FieldGTE(FieldFullSummary, v))
}

// FullSummaryLT applies the LT predicate on the "full_summary" field.
func FullSummaryLT(v string) predicate.Activity {
	return predicate.Activity(sql.FieldLT(FieldFullSummary, v))
}

// FullSummaryLTE applies the LTE predicate on the "full_summary" field.
func FullSummaryLTE(v string) predicate.Activity {
	return predicate.Activity(sql.FieldLTE(FieldFullSummary, v))
}

// FullSummaryContains applies the Contains predicate on the "full_summary" field.
func FullSummaryContains(v string) predicate.Activity {
	return predicate.Activity(sql.FieldContains(FieldFullSummary, v))
}

// FullSummaryHasPrefix applies the HasPrefix predicate on the "full_summary" field.
func FullSummaryHasPrefix(v string) predicate.Activity {
	return predicate.Activity(sql.FieldHasPrefix(FieldFullSummary, v))
}

// FullSummaryHasSuffix applies the HasSuffix predicate on the "full_summary" field.
func FullSummaryHasSuffix(v string) predicate.Activity {
	return predicate.Activity(sql.FieldHasSuffix(FieldFullSummary, v))
}

// FullSummaryEqualFold applies the EqualFold predicate on the "full_summary" field.
func FullSummaryEqualFold(v string) predicate.Activity {
	return predicate.Activity(sql.FieldEqualFold(FieldFullSummary, v))
}

// FullSummaryContainsFold applies the ContainsFold predicate on the "full_summary" field.
func FullSummaryContainsFold(v string) predicate.Activity {
	return predicate.Activity(sql.FieldContainsFold(FieldFullSummary, v))
}

// RawJSONEQ applies the EQ predicate on the "raw_json" field.
func RawJSONEQ(v string) predicate.Activity {
	return predicate.Activity(sql.FieldEQ(FieldRawJSON, v))
}

// RawJSONNEQ applies the NEQ predicate on the "raw_json" field.
func RawJSONNEQ(v string) predicate.Activity {
	return predicate.Activity(sql.FieldNEQ(FieldRawJSON, v))
}

// RawJSONIn applies the In predicate on the "raw_json" field.
func RawJSONIn(vs ...string) predicate.Activity {
	return predicate.Activity(sql.FieldIn(FieldRawJSON, vs...))
}

// RawJSONNotIn applies the NotIn predicate on the "raw_json" field.
func RawJSONNotIn(vs ...string) predicate.Activity {
	return predicate.Activity(sql.FieldNotIn(FieldRawJSON, vs...))
}

// RawJSONGT applies the GT predicate on the "raw_json" field.
func RawJSONGT(v string) predicate.Activity {
	return predicate.Activity(sql.FieldGT(FieldRawJSON, v))
}

// RawJSONGTE applies the GTE predicate on the "raw_json" field.
func RawJSONGTE(v string) predicate.Activity {
	return predicate.Activity(sql.FieldGTE(FieldRawJSON, v))
}

// RawJSONLT applies the LT predicate on the "raw_json" field.
func RawJSONLT(v string) predicate.Activity {
	return predicate.Activity(sql.FieldLT(FieldRawJSON, v))
}

// RawJSONLTE applies the LTE predicate on the "raw_json" field.
func RawJSONLTE(v string) predicate.Activity {
	return predicate.Activity(sql.FieldLTE(FieldRawJSON, v))
}

// RawJSONContains applies the Contains predicate on the "raw_json" field.
func RawJSONContains(v string) predicate.Activity {
	return predicate.Activity(sql.FieldContains(FieldRawJSON, v))
}

// RawJSONHasPrefix applies the HasPrefix predicate on the "raw_json" field.
func RawJSONHasPrefix(v string) predicate.Activity {
	return predicate.Activity(sql.FieldHasPrefix(FieldRawJSON, v))
}

// RawJSONHasSuffix applies the HasSuffix predicate on the "raw_json" field.
func RawJSONHasSuffix(v string) predicate.Activity {
	return predicate.Activity(sql.FieldHasSuffix(FieldRawJSON, v))
}

// RawJSONEqualFold applies the EqualFold predicate on the "raw_json" field.
func RawJSONEqualFold(v string) predicate.Activity {
	return predicate.Activity(sql.FieldEqualFold(FieldRawJSON, v))
}

// RawJSONContainsFold applies the ContainsFold predicate on the "raw_json" field.
func RawJSONContainsFold(v string) predicate.Activity {
	return predicate.Activity(sql.FieldContainsFold(FieldRawJSON, v))
}

// EmbeddingEQ applies the EQ predicate on the "embedding" field.
func EmbeddingEQ(v pgvector.Vector) predicate.Activity {
	return predicate.Activity(sql.FieldEQ(FieldEmbedding, v))
}

// EmbeddingNEQ applies the NEQ predicate on the "embedding" field.
func EmbeddingNEQ(v pgvector.Vector) predicate.Activity {
	return predicate.Activity(sql.FieldNEQ(FieldEmbedding, v))
}

// EmbeddingIn applies the In predicate on the "embedding" field.
func EmbeddingIn(vs ...pgvector.Vector) predicate.Activity {
	return predicate.Activity(sql.FieldIn(FieldEmbedding, vs...))
}

// EmbeddingNotIn applies the NotIn predicate on the "embedding" field.
func EmbeddingNotIn(vs ...pgvector.Vector) predicate.Activity {
	return predicate.Activity(sql.FieldNotIn(FieldEmbedding, vs...))
}

// EmbeddingGT applies the GT predicate on the "embedding" field.
func EmbeddingGT(v pgvector.Vector) predicate.Activity {
	return predicate.Activity(sql.FieldGT(FieldEmbedding, v))
}

// EmbeddingGTE applies the GTE predicate on the "embedding" field.
func EmbeddingGTE(v pgvector.Vector) predicate.Activity {
	return predicate.Activity(sql.FieldGTE(FieldEmbedding, v))
}

// EmbeddingLT applies the LT predicate on the "embedding" field.
func EmbeddingLT(v pgvector.Vector) predicate.Activity {
	return predicate.Activity(sql.FieldLT(FieldEmbedding, v))
}

// EmbeddingLTE applies the LTE predicate on the "embedding" field.
func EmbeddingLTE(v pgvector.Vector) predicate.Activity {
	return predicate.Activity(sql.FieldLTE(FieldEmbedding, v))
}

// EmbeddingIsNil applies the IsNil predicate on the "embedding" field.
func EmbeddingIsNil() predicate.Activity {
	return predicate.Activity(sql.FieldIsNull(FieldEmbedding))
}

// EmbeddingNotNil applies the NotNil predicate on the "embedding" field.
func EmbeddingNotNil() predicate.Activity {
	return predicate.Activity(sql.FieldNotNull(FieldEmbedding))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Activity) predicate.Activity {
	return predicate.Activity(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Activity) predicate.Activity {
	return predicate.Activity(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Activity) predicate.Activity {
	return predicate.Activity(sql.NotPredicates(p))
}
