// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/glanceapp/glance/pkg/storage/postgres/ent/predicate"
	"github.com/glanceapp/glance/pkg/storage/postgres/ent/source"
)

// SourceUpdate is the builder for updating Source entities.
type SourceUpdate struct {
	config
	hooks    []Hook
	mutation *SourceMutation
}

// Where appends a list predicates to the SourceUpdate builder.
func (su *SourceUpdate) Where(ps ...predicate.Source) *SourceUpdate {
	su.mutation.Where(ps...)
	return su
}

// SetName sets the "name" field.
func (su *SourceUpdate) SetName(s string) *SourceUpdate {
	su.mutation.SetName(s)
	return su
}

// SetNillableName sets the "name" field if the given value is not nil.
func (su *SourceUpdate) SetNillableName(s *string) *SourceUpdate {
	if s != nil {
		su.SetName(*s)
	}
	return su
}

// SetURL sets the "url" field.
func (su *SourceUpdate) SetURL(s string) *SourceUpdate {
	su.mutation.SetURL(s)
	return su
}

// SetNillableURL sets the "url" field if the given value is not nil.
func (su *SourceUpdate) SetNillableURL(s *string) *SourceUpdate {
	if s != nil {
		su.SetURL(*s)
	}
	return su
}

// SetType sets the "type" field.
func (su *SourceUpdate) SetType(s string) *SourceUpdate {
	su.mutation.SetType(s)
	return su
}

// SetNillableType sets the "type" field if the given value is not nil.
func (su *SourceUpdate) SetNillableType(s *string) *SourceUpdate {
	if s != nil {
		su.SetType(*s)
	}
	return su
}

// SetRawJSON sets the "raw_json" field.
func (su *SourceUpdate) SetRawJSON(s string) *SourceUpdate {
	su.mutation.SetRawJSON(s)
	return su
}

// SetNillableRawJSON sets the "raw_json" field if the given value is not nil.
func (su *SourceUpdate) SetNillableRawJSON(s *string) *SourceUpdate {
	if s != nil {
		su.SetRawJSON(*s)
	}
	return su
}

// Mutation returns the SourceMutation object of the builder.
func (su *SourceUpdate) Mutation() *SourceMutation {
	return su.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (su *SourceUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, su.sqlSave, su.mutation, su.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (su *SourceUpdate) SaveX(ctx context.Context) int {
	affected, err := su.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (su *SourceUpdate) Exec(ctx context.Context) error {
	_, err := su.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (su *SourceUpdate) ExecX(ctx context.Context) {
	if err := su.Exec(ctx); err != nil {
		panic(err)
	}
}

func (su *SourceUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := sqlgraph.NewUpdateSpec(source.Table, source.Columns, sqlgraph.NewFieldSpec(source.FieldID, field.TypeString))
	if ps := su.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := su.mutation.Name(); ok {
		_spec.SetField(source.FieldName, field.TypeString, value)
	}
	if value, ok := su.mutation.URL(); ok {
		_spec.SetField(source.FieldURL, field.TypeString, value)
	}
	if value, ok := su.mutation.GetType(); ok {
		_spec.SetField(source.FieldType, field.TypeString, value)
	}
	if value, ok := su.mutation.RawJSON(); ok {
		_spec.SetField(source.FieldRawJSON, field.TypeString, value)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, su.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{source.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	su.mutation.done = true
	return n, nil
}

// SourceUpdateOne is the builder for updating a single Source entity.
type SourceUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *SourceMutation
}

// SetName sets the "name" field.
func (suo *SourceUpdateOne) SetName(s string) *SourceUpdateOne {
	suo.mutation.SetName(s)
	return suo
}

// SetNillableName sets the "name" field if the given value is not nil.
func (suo *SourceUpdateOne) SetNillableName(s *string) *SourceUpdateOne {
	if s != nil {
		suo.SetName(*s)
	}
	return suo
}

// SetURL sets the "url" field.
func (suo *SourceUpdateOne) SetURL(s string) *SourceUpdateOne {
	suo.mutation.SetURL(s)
	return suo
}

// SetNillableURL sets the "url" field if the given value is not nil.
func (suo *SourceUpdateOne) SetNillableURL(s *string) *SourceUpdateOne {
	if s != nil {
		suo.SetURL(*s)
	}
	return suo
}

// SetType sets the "type" field.
func (suo *SourceUpdateOne) SetType(s string) *SourceUpdateOne {
	suo.mutation.SetType(s)
	return suo
}

// SetNillableType sets the "type" field if the given value is not nil.
func (suo *SourceUpdateOne) SetNillableType(s *string) *SourceUpdateOne {
	if s != nil {
		suo.SetType(*s)
	}
	return suo
}

// SetRawJSON sets the "raw_json" field.
func (suo *SourceUpdateOne) SetRawJSON(s string) *SourceUpdateOne {
	suo.mutation.SetRawJSON(s)
	return suo
}

// SetNillableRawJSON sets the "raw_json" field if the given value is not nil.
func (suo *SourceUpdateOne) SetNillableRawJSON(s *string) *SourceUpdateOne {
	if s != nil {
		suo.SetRawJSON(*s)
	}
	return suo
}

// Mutation returns the SourceMutation object of the builder.
func (suo *SourceUpdateOne) Mutation() *SourceMutation {
	return suo.mutation
}

// Where appends a list predicates to the SourceUpdate builder.
func (suo *SourceUpdateOne) Where(ps ...predicate.Source) *SourceUpdateOne {
	suo.mutation.Where(ps...)
	return suo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (suo *SourceUpdateOne) Select(field string, fields ...string) *SourceUpdateOne {
	suo.fields = append([]string{field}, fields...)
	return suo
}

// Save executes the query and returns the updated Source entity.
func (suo *SourceUpdateOne) Save(ctx context.Context) (*Source, error) {
	return withHooks(ctx, suo.sqlSave, suo.mutation, suo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (suo *SourceUpdateOne) SaveX(ctx context.Context) *Source {
	node, err := suo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (suo *SourceUpdateOne) Exec(ctx context.Context) error {
	_, err := suo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (suo *SourceUpdateOne) ExecX(ctx context.Context) {
	if err := suo.Exec(ctx); err != nil {
		panic(err)
	}
}

func (suo *SourceUpdateOne) sqlSave(ctx context.Context) (_node *Source, err error) {
	_spec := sqlgraph.NewUpdateSpec(source.Table, source.Columns, sqlgraph.NewFieldSpec(source.FieldID, field.TypeString))
	id, ok := suo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Source.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := suo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, source.FieldID)
		for _, f := range fields {
			if !source.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != source.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := suo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := suo.mutation.Name(); ok {
		_spec.SetField(source.FieldName, field.TypeString, value)
	}
	if value, ok := suo.mutation.URL(); ok {
		_spec.SetField(source.FieldURL, field.TypeString, value)
	}
	if value, ok := suo.mutation.GetType(); ok {
		_spec.SetField(source.FieldType, field.TypeString, value)
	}
	if value, ok := suo.mutation.RawJSON(); ok {
		_spec.SetField(source.FieldRawJSON, field.TypeString, value)
	}
	_node = &Source{config: suo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, suo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{source.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	suo.mutation.done = true
	return _node, nil
}
