name: Bug report
description: Let us know if something isn't working as expected
labels: ["bug report"]
body:
  - type: markdown
    attributes:
      value: |
        > [!NOTE]
        >
        > Do not prefix your title with "[BUG]", "[Bug report]", etc., a label will be added automatically.

        If you're unsure whether you're experiencing a bug or not, consider using the [Discussions](https://github.com/defeedco/defeed/discussions) to ask for help.

        Please include only the information you think is relevant to the bug.

  - type: textarea
    id: description
    validations:
      required: true
    attributes:
      label: Description

  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to submit a bug report.
