name: Feature request
description: Share your ideas for new features or improvements
labels: ["feature request"]
body:
  - type: markdown
    attributes:
      value: |
        > [!NOTE]
        >
        > Do not prefix your title with "[REQUEST]", "[Feature request]", etc., a label will be added automatically.

        Please provide a detailed description of what the feature would do and what it would look like.

  - type: textarea
    id: description
    validations:
      required: true
    attributes:
      label: Description

  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to submit your idea.
