// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// ActivitiesColumns holds the columns for the "activities" table.
	ActivitiesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString, Unique: true},
		{Name: "uid", Type: field.TypeString, Unique: true},
		{Name: "source_uid", Type: field.TypeString},
		{Name: "source_type", Type: field.TypeString},
		{Name: "title", Type: field.TypeString},
		{Name: "body", Type: field.TypeString},
		{Name: "url", Type: field.TypeString},
		{Name: "image_url", Type: field.TypeString},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "short_summary", Type: field.TypeString},
		{Name: "full_summary", Type: field.TypeString},
		{Name: "raw_json", Type: field.TypeString},
		{Name: "embedding_1536", Type: field.TypeOther, Nullable: true, SchemaType: map[string]string{"postgres": "vector(1536)"}},
		{Name: "embedding_3072", Type: field.TypeOther, Nullable: true, SchemaType: map[string]string{"postgres": "vector(3072)"}},
		{Name: "social_score", Type: field.TypeFloat64, Default: -1},
		{Name: "update_count", Type: field.TypeInt, Default: 0},
	}
	// ActivitiesTable holds the schema information for the "activities" table.
	ActivitiesTable = &schema.Table{
		Name:       "activities",
		Columns:    ActivitiesColumns,
		PrimaryKey: []*schema.Column{ActivitiesColumns[0]},
	}
	// FeedsColumns holds the columns for the "feeds" table.
	FeedsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString, Unique: true},
		{Name: "user_id", Type: field.TypeString},
		{Name: "name", Type: field.TypeString},
		{Name: "icon", Type: field.TypeString},
		{Name: "query", Type: field.TypeString},
		{Name: "public", Type: field.TypeBool},
		{Name: "source_uids", Type: field.TypeJSON},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// FeedsTable holds the schema information for the "feeds" table.
	FeedsTable = &schema.Table{
		Name:       "feeds",
		Columns:    FeedsColumns,
		PrimaryKey: []*schema.Column{FeedsColumns[0]},
	}
	// SourcesColumns holds the columns for the "sources" table.
	SourcesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString, Unique: true},
		{Name: "name", Type: field.TypeString},
		{Name: "url", Type: field.TypeString},
		{Name: "type", Type: field.TypeString},
		{Name: "raw_json", Type: field.TypeString},
	}
	// SourcesTable holds the schema information for the "sources" table.
	SourcesTable = &schema.Table{
		Name:       "sources",
		Columns:    SourcesColumns,
		PrimaryKey: []*schema.Column{SourcesColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		ActivitiesTable,
		FeedsTable,
		SourcesTable,
	}
)

func init() {
}
